//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeelu {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XhtmlRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XhtmlRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jeelu.Xhtml.XhtmlRes", typeof(XhtmlRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;att&gt;
        ///  &lt;target&gt;
        ///    &lt;e k=&quot;_top&quot;&gt;_top&lt;/e&gt;
        ///    &lt;e k=&quot;_parent&quot;&gt;_parent&lt;/e&gt;
        ///    &lt;e k=&quot;_self&quot;&gt;_self&lt;/e&gt;
        ///    &lt;e k=&quot;_blank&quot;&gt;_blank&lt;/e&gt;
        ///  &lt;/target&gt;
        ///  &lt;charset&gt;
        ///    &lt;e k=&quot;_iso_8859_1&quot;&gt;iso-8859-1&lt;/e&gt;
        ///    &lt;e k=&quot;utf_8&quot;&gt;utf-8&lt;/e&gt;
        ///    &lt;e k=&quot;shift_j_is&quot;&gt;shift_jis&lt;/e&gt;
        ///    &lt;e k=&quot;euc_jp&quot;&gt;euc-jp&lt;/e&gt;
        ///    &lt;e k=&quot;big5&quot;&gt;big5&lt;/e&gt;
        ///    &lt;e k=&quot;gb2312&quot;&gt;gb2312&lt;/e&gt;
        ///    &lt;e k=&quot;euc_kr&quot;&gt;euc-kr&lt;/e&gt;
        ///    &lt;e k=&quot;din_66003_kr&quot;&gt;din_66003-kr&lt;/e&gt;
        ///    &lt;e k=&quot;ns_4551_1_kr&quot;&gt;ns_4551-1-kr&lt;/e&gt;
        ///    &lt;e k=&quot;sen_850200_b&quot;&gt;sen_850200_b&lt;/e&gt;
        ///    &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string attEnum {
            get {
                return ResourceManager.GetString("attEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h1 style=&quot;visibility:hidden;&quot;&gt;Power by:&lt;a href=&quot;http://www.Jeelu.com&quot; title=&quot;广告联播,捷报频传&quot;&gt;捷报&lt;/a&gt;,&lt;a href=&quot;http://www.Jeelu.com&quot; title=&quot;Jeelu&quot;&gt;Jeelu&lt;/a&gt;,&lt;a href=&quot;http://www.SimplusD.com&quot; title=&quot;网站360°&quot;&gt;网站360°&lt;/a&gt;&lt;/h1&gt; 的本地化字符串。
        /// </summary>
        internal static string JeeluCode {
            get {
                return ResourceManager.GetString("JeeluCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Tags&gt;
        ///  &lt;tag attribute=&quot;tag&quot;&gt;a&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;href&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;name&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;title&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;target&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;charset&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;class&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;id&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;style&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;hreflang&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;accesskey&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;tabindex&lt;/tag&gt;
        ///  &lt;tag attribute=&quot;attrib&quot;&gt;rel&lt;/tag&gt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tagname {
            get {
                return ResourceManager.GetString("tagname", resourceCulture);
            }
        }
    }
}
