//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.CoreConsole {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Example.CoreConsole.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 人民教育出版社
        ///中国少年儿童新闻出版总社
        ///外语教学与研究出版社
        ///北京师范大学出版社
        ///上海世纪出版集团
        ///科学出版社
        ///电子工业出版社
        ///化学工业出版社
        ///机械工业出版社
        ///中国地图出版社
        ///人民邮电出版社
        ///上海译文出版社
        ///中国劳动社会保障出版社
        ///中华书局
        ///高等教育出版社
        ///中国水利水电出版社
        ///商务印书馆
        ///知识产权出版社
        ///中国人民大学出版社
        ///清华大学出版社
        ///人民文学出版社
        ///语文出版社
        ///中国致公出版社
        ///中国建筑工业出版社
        ///法律出版社
        ///中国电力出版社
        ///北京语言大学出版社
        ///外文出版社
        ///人民卫生出版社
        ///武汉大学出版社 的本地化字符串。
        /// </summary>
        internal static string PublisherList {
            get {
                return ResourceManager.GetString("PublisherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 人员名单资料 {
            get {
                object obj = ResourceManager.GetObject("人员名单资料", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 图书目录资料 {
            get {
                object obj = ResourceManager.GetObject("图书目录资料", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
