<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>24.0.1</AssemblyVersion>
    <FileVersion>24.0.1</FileVersion>
    <Version>24.0.1</Version>
    <Authors>lukan@xknife.net</Authors>
    <Company>xknife.net</Company>
    <Description>一个面向.Net的综合开发库。</Description>
    <Copyright>Copyright © 2008 - $([System.DateTime]::Today.ToString(yyyy)) xknife.net.</Copyright>
    <Product>$(AssemblyName)</Product>
    <Title>$(AssemblyName)</Title>
    <PackageProjectUrl>https://gitee.com/xknife/nknife</PackageProjectUrl>
    <RepositoryUrl>https://gitee.com/xknife/nknife</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\**" />
    <Compile Remove="ShareResources\**" />
    <EmbeddedResource Remove="Properties\**" />
    <EmbeddedResource Remove="ShareResources\**" />
    <None Remove="Properties\**" />
    <None Remove="ShareResources\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Common" Version="8.2.2" />
    <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.2.2" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.2.2" />
  </ItemGroup>

  <ItemGroup>
      <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
